// Copyright (C) 2024 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

#pragma once

#define XPUINFO_API_VERSION_MAJOR 1
#define XPUINFO_API_VERSION_MINOR 0
#define XPUINFO_API_VERSION_PATCH 0
#define XPUINFO_API_VERSION ((XPUINFO_API_VERSION_MAJOR * 10000) + (XPUINFO_API_VERSION_MINOR * 100) + XPUINFO_API_VERSION_PATCH)

#define XPUINFO_TEXTIFY2(x) #x
#define XPUINFO_TEXTIFY(x) XPUINFO_TEXTIFY2(x)

#define XPUINFO_API_VERSION_STRING XPUINFO_TEXTIFY(XPUINFO_API_VERSION_MAJOR) "." XPUINFO_TEXTIFY(XPUINFO_API_VERSION_MINOR) "." XPUINFO_TEXTIFY(XPUINFO_API_VERSION_PATCH)

// Allow client override
#ifndef XPUINFO_BUILD_TIMESTAMP
    #define XPUINFO_BUILD_TIMESTAMP __DATE__ " " __TIME__
#endif // XPUINFO_BUILD_TIMESTAMP

#ifdef XPUINFO_USE_RAPIDJSON
    // Allow client override as preprocessor literal, but stringify it
    #ifndef XPUINFO_JSON_VERSION_LITERAL
        #define XPUINFO_JSON_VERSION XPUINFO_API_VERSION_STRING
    #else
        #define XPUINFO_JSON_VERSION XPUINFO_TEXTIFY(XPUINFO_JSON_VERSION_LITERAL)
    #endif
#endif // XPUINFO_USE_RAPIDJSON
